# Generated by Django 4.2.7 on 2023-11-22 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Userapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMoney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.IntegerField(default=8600)),
                ('expired_date', models.DateField()),
                ('money', models.IntegerField()),
                ('card_holder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Userapp.user')),
            ],
        ),
    ]
